# Generated by Django 3.1.3 on 2020-11-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('document_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=140)),
            ],
            options={
                'db_table': 'providers',
            },
        ),
    ]
