# Generated by Django 3.1.3 on 2020-11-29 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('document_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=140)),
            ],
            options={
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('price', models.FloatField()),
                ('providers_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='providers_id', to='products_providers.providers')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
