# Generated by Django 3.1.3 on 2020-11-29 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('price', models.FloatField()),
                ('providers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='providers_id', to='providers.providers')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
